classdef CommModularContainer < handle
    properties
        containerSize = 0;
        classID = 0;       % What device type is this?
        actorNumber = 0;   % Increment if there are more than one of the same device ID
        actorFunction = 0; % Command/reponse
        payload = [];

        BASE_CONTAINER_SIZE = 13;

        ID_GENERIC_ACTOR_SPAWNER = 135;

        FCN_GENERIC_ACTOR_SPAWNER_SPAWN_ID = 10;
        FCN_GENERIC_ACTOR_SPAWNER_SPAWN_ID_ACK = 11;
        FCN_GENERIC_ACTOR_SPAWNER_DESTROY_ACTOR = 12;
        FCN_GENERIC_ACTOR_SPAWNER_DESTROY_ACTOR_ACK = 13;
        FCN_GENERIC_ACTOR_SPAWNER_DESTROY_ALL_ACTORS_OF_CLASS = 24;
        FCN_GENERIC_ACTOR_SPAWNER_DESTROY_ALL_ACTORS_OF_CLASS_ACK = 25;
        FCN_GENERIC_ACTOR_SPAWNER_DESTROY_ALL_SPAWNED_ACTORS = 14;
        FCN_GENERIC_ACTOR_SPAWNER_DESTROY_ALL_SPAWNED_ACTORS_ACK = 15;
        FCN_GENERIC_ACTOR_SPAWNER_REGENERATE_CACHE_LIST = 16;
        FCN_GENERIC_ACTOR_SPAWNER_REGENERATE_CACHE_LIST_ACK = 17;
        FCN_GENERIC_ACTOR_SPAWNER_SPAWN = 22;
        FCN_GENERIC_ACTOR_SPAWNER_SPAWN_RESPONSE = 23;
        FCN_GENERIC_ACTOR_SPAWNER_SPAWN_AND_PARENT_RELATIVE = 50;
        FCN_GENERIC_ACTOR_SPAWNER_SPAWN_AND_PARENT_RELATIVE_ACK = 51;
        FCN_GENERIC_ACTOR_SPAWNER_PARENT_CURRENT_WORLD = 52;
        FCN_GENERIC_ACTOR_SPAWNER_PARENT_CURRENT_WORLD_ACK = 53;
        FCN_GENERIC_ACTOR_SPAWNER_PARENT_RELATIVE = 54;
        FCN_GENERIC_ACTOR_SPAWNER_PARENT_RELATIVE_ACK = 55;
        FCN_GENERIC_ACTOR_SPAWNER_PARENT_BREAK_WITH_CURRENT_WORLD = 56;
        FCN_GENERIC_ACTOR_SPAWNER_PARENT_BREAK_WITH_CURRENT_WORLD_ACK = 57;
    end
end